# Technical configuration for notebooks and internal processes.
# This file contains constants that users rarely need to modify.

paths:
  # Folder created during the process
  tmp_folder: "../tmp_files"
  # Filenames for internal/generated files
  local_config_file: "config_repo.ttl"
  pref_hidden_labels_file: "pref_hidden_labels.ttl"
  comparisons_file: "comparisons.ttl"

named_graphs:
  # Internal identifiers for GraphDB named graphs
  ontology: "ontology"
  facts: "facts"
  inter_sources: "inter_sources"
  comparisons: "comparisons"
  labels: "labels"
  temporary: "temporary"
  metadata: "metadata"

labels:
  # Metadata for the UI or logs
  facts_label: "Faits construits à partir des sources"
  lang: "fr"

comparison_settings:
  # Geometric comparison parameters
  geom_similarity_coef: 0.85
  geom_buffer_radius: 10
  geom_crs_uri: "http://www.opengis.net/def/crs/EPSG/0/2154"
  epsg_code: "EPSG:2154"

namespaces:
    # Namespaces for RDF construction
    PEG: "https://w3id.org/PeGazUs/id/"
    ATYPE: "https://w3id.org/PeGazUs/id/codes/AttributeType/"
    CTYPE: "https://w3id.org/PeGazUs/id/codes/ChangeType/"
    LTYPE: "https://w3id.org/PeGazUs/id/codes/LandmarkType/"
    LRTYPE: "https://w3id.org/PeGazUs/id/codes/LandmarkRelationType/"
    RES: "https://w3id.org/PeGazUs/id/"
    GRAPH: "https://w3id.org/PeGazUs/id/Graph/"
    TIME: "http://www.w3.org/2006/time#"
    PROV: "http://www.w3.org/ns/prov#"
    RICO: "https://www.ica.org/standards/RiC/ontology#"
    GEO: "http://www.opengis.net/ont/geosparql#"
    GEOFLA: "http://data.ign.fr/def/geofla#"
    WD: "http://www.wikidata.org/entity/"
    SKOS: "http://www.w3.org/2004/02/skos/core#"
    RDF: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    RDFS: "http://www.w3.org/2000/01/rdf-schema#"
    XSD: "http://www.w3.org/2001/XMLSchema#"
    OWL: "http://www.w3.org/2002/07/owl#"
    OFN: "http://www.ontotext.com/sparql/functions/"